import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Footer } from '@/components/footer'
import { Toaster } from '@/components/ui/sonner'
import { Providers } from '@/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Vintage barber',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <div className="flex h-full flex-col">
            <div className="flex-1 pb-4">{children}</div>
            <Footer />
          </div>
        </Providers>
        <Toaster position="top-right" theme="dark" />
      </body>
    </html>
  )
}
